export class Suppliers {
  constructor(
    public supplier_ID: any,
    public supplier_Name: any, 
    public supplierCategory: any,
    public contact_ID: any,
    public contact_Name: any,
    public contact_Phone: any,
    public contact_Cell: any,
    public cell: any,
    public phone: any,
    public fax: any,
    public ntn: any,
    public email: any,
    public website: any,
    public credit_Limit: any,
    public credit_Hold: any,
    public payment_Term: any,
    public freight_Term: any,
    public industary: any,
    public ownership: any,
    public balanceAmount: any,
    public balanceType: any,
    public remarks: any,
    public exchange: any,
    public customer_ID: any,
    public sGUID: any,
    public addresS_ID: any,
    public addresS_Line1: any,
    public addresS_Line2: any,
    public addresS_Line3: any,
    public citY_CODE: any,
    public statE_CODE: any,
    public countarY_Code: any,
    public status: any,
    
    public createD_BY: any,    
    public userSessionID: any,
    //public taxcode: any,
  ) { }
}
