
export class Employee {
  constructor(
    public emP_ID: any,
    public firsT_NAME: any,
    public middlE_NAME: any,
    public lasT_NAME: any,
    public fatheR_NAME: any,
    public cnic: any,
    public gendeR_ID: any,
    public maritaL_STATUS_ID: any,
    public eobI_NO: any,
    public glI_NO: any,
    public sociaL_SECURITY_NO: any,
    public birthplace: any,
    public countrY_ID: any,
    public religion: any,
    public remarks: any,
    public correspondinG_ADDRESS: any,
    public psline1: any,
    public psline2: any,
    public psline3: any,
    public pscitycode: any,
    public pmline1: any,
    public pmline2: any,
    public pmline3: any,
    public pmcitycode: any,
    public phone: any,
    public mobile: any,
    public email: any,
    public officE_CODE: any,
    public departmenT_CODE: any,
    public designatioN_CODE: any,
    public employmenT_TYPE_ID: any,
    public categorY_CODE: any,
    public gradE_ID: any,
    public joB_STATUS_ID: any,
    public dob: any,
    public joininG_DATE: any,
    public contracT_END_DATE: any,
    public confirmatioN_DATE: any,
    public createdby: any,
    public empimage: any,
    public userSessionID: any,
  ) { }
}
