import { openingBalanceDetails } from './openingBalanceDetails';
export class openingBalance {
  constructor(
    
    public voucher_ID: any,
    public voucheR_NO: any,
    public voucheR_DATE: any,
    public oPBAL_DATE: any,
    public officE_CODE: any,
    public banK_CODE: any,
    public brancH_CODE: any,
    public chequE_NO: any,
    public chequE_DATE: any,
    public pay_To: any,
    public cancel: any,    
    public voucheR_TYPE_CODE: any,
    public invoice_Amt: any,
    public net_Paied: any,
    public invoice_No: any,
    public bank_Acct_No: any,
    public page_Code: any,
    public voucher_GUID: any,
    public pay_Method,     
    public vendor: any,
    public customerCode: any,
    public remarks: any,
    public approvE_BY: any,
    public approvE_DATE: any,
    public created_By: any,
    public userSessionID: any, 
    public accounT_CODE: any,
    public accounT_TITLE: any,
    public debit: any,
    public credit: any,
    public particulars: any,
    public projecT_CODE: any,
    public donoR_CODE: any,
    public cosT_CENTER_CODE: any,
    public abbr: any,
    public cosT_CENTER_TYPE: any,
    public currencY_CODE: any,
    public exchangE_RATE: any,
    public supplierCode: any,
    public sectoR_CODE: any,
    public servicE_CODE: any,
    public edit_Mode: any,
    public voucherDetails: openingBalanceDetails[],
    public fin_YR: any,
    public itemCode: any,
    public isUpdateable: any
  ) { }
}


